// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/about.tsx";
import * as $1 from "./routes/api/media/audiobooks.ts";
import * as $2 from "./routes/api/media/chapters.ts";
import * as $3 from "./routes/api/media/ebooks.ts";
import * as $4 from "./routes/api/media/index.ts";
import * as $5 from "./routes/api/media/volumes.ts";
import * as $6 from "./routes/index.tsx";
import * as $7 from "./routes/toc-beta.tsx";
import * as $8 from "./routes/toc.tsx";
import * as $$0 from "./islands/ChatContainer.tsx";
import * as $$1 from "./islands/ChatHelper.tsx";
import * as $$2 from "./islands/DropdownSelector.tsx";
import * as $$3 from "./islands/TableHeaderSorter.tsx";
import * as $$4 from "./islands/TableOfContents.tsx";
import * as $$5 from "./islands/TableOfContentsBeta.tsx";

const manifest = {
  routes: {
    "./routes/about.tsx": $0,
    "./routes/api/media/audiobooks.ts": $1,
    "./routes/api/media/chapters.ts": $2,
    "./routes/api/media/ebooks.ts": $3,
    "./routes/api/media/index.ts": $4,
    "./routes/api/media/volumes.ts": $5,
    "./routes/index.tsx": $6,
    "./routes/toc-beta.tsx": $7,
    "./routes/toc.tsx": $8,
  },
  islands: {
    "./islands/ChatContainer.tsx": $$0,
    "./islands/ChatHelper.tsx": $$1,
    "./islands/DropdownSelector.tsx": $$2,
    "./islands/TableHeaderSorter.tsx": $$3,
    "./islands/TableOfContents.tsx": $$4,
    "./islands/TableOfContentsBeta.tsx": $$5,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
