// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/about.tsx";
import * as $1 from "./routes/api/brackets/from-chapters.ts";
import * as $2 from "./routes/api/brackets/per-chapter.ts";
import * as $3 from "./routes/api/brackets/total.ts";
import * as $4 from "./routes/api/brackets/with-chapters.ts";
import * as $5 from "./routes/api/media/audiobooks.ts";
import * as $6 from "./routes/api/media/chapters.ts";
import * as $7 from "./routes/api/media/ebooks.ts";
import * as $8 from "./routes/api/media/index.ts";
import * as $9 from "./routes/api/media/volumes.ts";
import * as $10 from "./routes/brackets.tsx";
import * as $11 from "./routes/charts/media/word-count.ts";
import * as $12 from "./routes/charts/media/words-covered.ts";
import * as $13 from "./routes/charts/media/words-per-year.ts";
import * as $14 from "./routes/gazi.tsx";
import * as $15 from "./routes/index.tsx";
import * as $16 from "./routes/toc-beta.tsx";
import * as $17 from "./routes/toc.tsx";
import * as $$0 from "./islands/ChatContainer.tsx";
import * as $$1 from "./islands/ChatHelper.tsx";
import * as $$2 from "./islands/DropdownSelector.tsx";
import * as $$3 from "./islands/InteractiveGazi.tsx";
import * as $$4 from "./islands/TableHeaderSorter.tsx";
import * as $$5 from "./islands/TableOfBrackets.tsx";
import * as $$6 from "./islands/TableOfContents.tsx";
import * as $$7 from "./islands/TableOfContentsBeta.tsx";
import * as $$8 from "./islands/WanderingSiteLogo.tsx";

const manifest = {
  routes: {
    "./routes/about.tsx": $0,
    "./routes/api/brackets/from-chapters.ts": $1,
    "./routes/api/brackets/per-chapter.ts": $2,
    "./routes/api/brackets/total.ts": $3,
    "./routes/api/brackets/with-chapters.ts": $4,
    "./routes/api/media/audiobooks.ts": $5,
    "./routes/api/media/chapters.ts": $6,
    "./routes/api/media/ebooks.ts": $7,
    "./routes/api/media/index.ts": $8,
    "./routes/api/media/volumes.ts": $9,
    "./routes/brackets.tsx": $10,
    "./routes/charts/media/word-count.ts": $11,
    "./routes/charts/media/words-covered.ts": $12,
    "./routes/charts/media/words-per-year.ts": $13,
    "./routes/gazi.tsx": $14,
    "./routes/index.tsx": $15,
    "./routes/toc-beta.tsx": $16,
    "./routes/toc.tsx": $17,
  },
  islands: {
    "./islands/ChatContainer.tsx": $$0,
    "./islands/ChatHelper.tsx": $$1,
    "./islands/DropdownSelector.tsx": $$2,
    "./islands/InteractiveGazi.tsx": $$3,
    "./islands/TableHeaderSorter.tsx": $$4,
    "./islands/TableOfBrackets.tsx": $$5,
    "./islands/TableOfContents.tsx": $$6,
    "./islands/TableOfContentsBeta.tsx": $$7,
    "./islands/WanderingSiteLogo.tsx": $$8,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
